### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by Bubblejet** [OffensivePython/Saddam#1]
Testing this out on Kali (Debian) Linux with Python 2.7.3  
getting error message:  
"File './Saddam.py', line 9, in <module>
from pinject import IP, UDP
ImportError: cannot import name IP

**Comment by Bubblejet** [comment]
was getting error message because pinject was in the wrong folder apparently  :)

**Comment by viperbluff** [comment]
i am getting the same issue , what changes did you make ?

**Comment by Beyarz** [comment]
He moved the pinject file to the right directory.
