### ISSUE TITLE
Doesnt do more then one run

### ISSUE THREAD

**Issue by Ghorix** [OffensivePython/Saddam#11]
So i try to use Saddam.py and i have pinject. I can benchmark and in my unbound i see that the request. This all works fine. But now i have a problem that when i do an "Attack" i only see all the "domains" requested one time.

This makes that is doesn/t push any "real" load. Anyone here who got it working with his own unbound server?

**Comment by merkjinx** [comment]
Can you send screenshots of what you are talking about. So I can better understand

**Comment by Ghorix** [comment]
I solved the problem. I Did a TCP-Dump on both sides. It seems the local network that is used was  AlIP-SPOOFING-Protected. So only 1 packet got to the DNS-Server. Al the others got dropped at the switch.

Thank u for reacting.

At this moment i got it running on 8 nodes and are able to push some real load. This script works :dancer:
