### ISSUE TITLE
Speed 0

### ISSUE THREAD

**Issue by Nolovenodie** [OffensivePython/Saddam#25]
_____           __    __              
	  / ___/____ _____/ /___/ /___ _____ ___ 
	  \__ \/ __ `/ __  / __  / __ `/ __ `__ \
	 ___/ / /_/ / /_/ / /_/ / /_/ / / / / / /
	/____/\__,_/\__,_/\__,_/\__,_/_/ /_/ /_/ 
	https://github.com/OffensivePython/Saddam
	   https://twitter.com/OffensivePython

     Sent      |    Traffic    |    Packet/s   |     Bit/s     
     0.00      |     0.00B     |    0.00pps    |    0.00bps 
Any help?

**Comment by ilovedogs1235** [comment]
wow you've given so much information for somebody to assist you great job
