### ISSUE TITLE
Pinject Module

### ISSUE THREAD

**Issue by Etosticity** [OffensivePython/Saddam#8]
When I run the program, they always say that the pinject module is missing. I went to Google and searched; tried downloading and installing and it still gave me the same error. Can anyone help me?

**Comment by merkjinx** [comment]
if you are still having this problem. make sure that pinject is in the same file as saddam. here's the link the i used to download pinject https://github.com/OffensivePython/Pinject

**Comment by Etosticity** [comment]
Oh so the Pinject file must be in the same folder as Saddam? I'm kinda confused because I thought when you import a module, it must be in the Python Libs

**Comment by merkjinx** [comment]
there are two types of imports the python libraries and local files. python libraries are like your essential function such as threading or raw socket. the local import add functions that the user defines. in our case pinject... hope that helps.

**Comment by Etosticity** [comment]
Yep that helped me. Thanks ^_^
